---
kind: pipeline
type: kubernetes
name: backend

steps:
- name: test
  image: rustlang/rust:nightly-slim #ekidd/rust-musl-builder:nightly-2019-07-08
  user: root
  privileged: true
  commands:
#    - sudo chown -R rust:rust .
    - apt update
    - apt install -y pkg-config libssl-dev libpq-dev
    - cp -R ./* /home
    - cd /home
    - cargo build
    - cargo test
