---
kind: pipeline
type: kubernetes
name: backend

steps:
- name: test
  image: nhyne/rust-musl-builder-sccache:nightly-2019-07-08
  user: root
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: build_cache_aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: build_cache_aws_secret_access_key
    SCCACHE_BUCKET:
      from_secret: build_cache_bucket
    RUSTC_WRAPPER: sccache
  commands:
    - sudo cp -R ./* /home/rust/src
    - sudo chown -R rust:rust /home/rust/src
    - cd /home/rust/src
    - sccache --start-server
    - cargo build
    - cargo test
