---
kind: pipeline
type: kubernetes
name: backend

steps:
- name: test
  image: ekidd/rust-musl-builder:nightly-2019-07-08
  commands:
    - sudo chown -R rust:rust .
    - cargo build
    - cargo test
