---
kind: pipeline
type: kubernetes
name: backend

steps:
- name: chown
  image: rustlang/rust:nightly-slim
  commands:
    - chown
  args:
    - "rust:rust"
    - "-R"
    - "/drone/src/target/debug/build"

- name: test
  image: rustlang/rust:nightly-slim
  commands:
  - cargo test
