name: CI Build
on:
  push:
    tags:
      - 'nightly-20*'
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      TAG: ${{ github.ref }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
      DOCKER_USERNAME: ${{ secrets.docker_username }}
    steps:
      - uses: actions/checkout@v1
      - name: build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          LOCAL_TAG=$(echo $TAG | cut -d '/' -f3)
          docker build -t "nhyne/nightly-rust-ci:$LOCAL_TAG" -f CIDockerfile .
          docker login -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
          docker push "nhyne/nightly-rust-ci:$LOCAL_TAG"
