name: Sccache Build
on:
  push:
    tags:
      - 'postgres*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
      DOCKER_USERNAME: ${{ secrets.docker_username }}
    steps:
      - uses: actions/checkout@v1
      - name: build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          LOCAL_TAG=$(echo $TAG | cut -d '/' -f3)
          docker build -t "nhyne/diesel-cli:$LOCAL_TAG" -f DieselDockerfile .
          docker login -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
          docker push "nhyne/diesel-cli:$LOCAL_TAG"
      - name: debug event
        env:
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref }}
        run: |
          echo $EVENT
          echo $REF
