name: Sccache Build
on:
  push:
    tags:
      - 'nightly-20*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
      DOCKER_USERNAME: ${{ secrets.docker_username }}
    steps:
      - uses: actions/checkout@v1
      - name: build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          LOCAL_TAG=$(echo $TAG | cut -d '/' -f3)
          docker build -t "nhyne/rust-musl-builder-sccache:$LOCAL_TAG" -f SccacheDockerfile .
          docker login -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
          docker push "nhyne/rust-musl-builder-sccache:$LOCAL_TAG"
