name: Cargo Test
on: push
  # push:
  #   paths:
  #     - 'src/**.rs'
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nhyne/rust-musl-builder-sccache:nightly-2019-09-05
    steps:
      - uses: actions/checkout@v1
      - name: test
        env:
          RUSTC_WRAPPER: sccache
          AWS_ACCESS_KEY_ID: ${{ secrets.build_cache_aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.build_cache_aws_secret_access_key }}
          SCCACHE_BUCKET: nhyne-build-cache
        run: cargo test --verbose

